/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

val stellarSdkVersion = "0.35.0"
val ktorVersion = "2.3.8" // O la versión que uses
val kotlinVersion = "1.9.22"

dependencies {
// Implementación de la librería Kotlin (anteriormente libs.kotlin.gradle.plugin)
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion") 

    // Línea 21: java-stellar-sdk
    implementation("org.stellar:java-stellar-sdk:$stellarSdkVersion") 
    
    // Línea 22: Dependencias Ktor
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
    implementation("io.ktor:ktor-server-core:$ktorVersion")
    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktorVersion")
    
    // Línea 25 (anteriormente): Ahora debería estar aquí
    implementation("io.ktor:ktor-server-content-negotiation:$ktorVersion")

}
