/*
 * This file was generated by the Gradle 'init' task.
 *
 * This settings file is used to specify which projects to include in your build-logic build.
 * This project uses @Incubating APIs which are subject to change.
 */


dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral() // <--- ¡Asegúrate de que esta línea esté presente!
        maven("https://jitpack.io") // Opcional, pero a veces útil
        
        // Si tu proyecto es multiplatform (Compose Multiplatform), también podrías necesitar:
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev") 
    }

    
}

rootProject.name = "build-logic"
